using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Epoxid.SourceGeneration.Generators;

[Generator]
public class EpoxidTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Epoxid.SourceGeneration.EpoxidTypeAttribute",
                predicate: generatorCandidate,
                transform: createTarget)
            .Where(t => t != null);

        context.RegisterSourceOutput(pipeline, emitFile);
    }

    private const string generated_code_attribute = "[global::System.CodeDom.Compiler.GeneratedCode(\"Epoxid.SourceGeneration\", null)]";
    private const string slot_offset = "global::Epoxid.Runtime.SlotOffset";
    private const string readonly_dictionary_string_offset = $"global::System.Collections.ObjectModel.ReadOnlyDictionary<string, {slot_offset}>";
    private const string dictionary_string_offset = $"global::System.Collections.Generic.Dictionary<string, {slot_offset}>";

    private static bool generatorCandidate(SyntaxNode node, CancellationToken ct)
    {
        if (node is not ClassDeclarationSyntax cl)
            return false;

        if (!cl.Modifiers.Any(SyntaxKind.PartialKeyword))
            return false;

        return true;
    }

    private static TargetData? createTarget(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not ITypeSymbol target)
            return null;

        if (target.BaseType == null)
            return null;

        var slots = ImmutableArray.CreateBuilder<SlotData>();
        foreach (var member in target.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.GetMethod == null || member.SetMethod == null)
                continue;

            var slotAttribute = member.GetAttributes().FirstOrDefault(SyntaxHelpers.IsSlotAttribute);
            if (slotAttribute is not AttributeData attr)
                continue;

            string propertyName = member.Name;
            string descriptorName = (string)attr.ConstructorArguments[0].Value!;
            string typeName = SyntaxHelpers.GetGlobalQualifiedName(member.Type);

            slots.Add(new(
                propertyName,
                descriptorName,
                typeName,
                member.Type.NullableAnnotation == NullableAnnotation.Annotated,
                member.DeclaredAccessibility,
                member.GetMethod.DeclaredAccessibility,
                member.SetMethod.DeclaredAccessibility));
        }

        return new TargetData(
            target.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)),
            target.Name,
            target.BaseType.Name,
            new ValueArray<SlotData>(slots.ToImmutable())
        );
    }

    private static void emitFile(SourceProductionContext context, TargetData? target)
    {
        if (target == null)
            return;

        var builder = new SourceBuilder();

        builder.AddLines("""
        // <auto-generated />
        // Bau bau software engineering

        #nullable enable
        """);

        builder.AddLine($"namespace {target.Namespace};");

        builder.AddLine($"partial class {target.ClassName}");

        using (builder.BlockScope())
        {
            builder.AddLines($"""
            // Slots count of '{target.ClassName}' type.
            {generated_code_attribute}
            protected const int {classSlotCount(target.ClassName)} = {classSlotCount(target.BaseClassName)} + {target.Slots.Length};

            {generated_code_attribute}
            private protected override int SlotsCount => {classSlotCount(target.ClassName)};
            """);

            builder.AddLines($"""
            {generated_code_attribute}
            private static readonly {readonly_dictionary_string_offset} slot_descriptors_mapping = new {dictionary_string_offset}
            """);
            using (builder.BlockScope(".AsReadOnly();"))
            {
                foreach (var slot in target.Slots)
                {
                    builder.AddLine($"[\"{slot.DescriptorName}\"] = new {slot_offset}({slotIndex(slot.PropertyName)}),");
                }
            }

            for (int i = 0; i < target.Slots.Length; i++)
            {
                builder.BlankLine();
                var slot = target.Slots[i];

                string accessibility = getAccessibilityString(slot.PropertyAccessibility);
                string getAccess = getAccessibilityString(slot.GetAccessibility);
                string setAccess = getAccessibilityString(slot.SetAccessibility);

                builder.AddLines($"""
                // Property of the '{slot.DescriptorName}' slot
                {generated_code_attribute}
                {accessibility} partial {slot.TypeString} {slot.PropertyName}
                """);

                using (builder.BlockScope())
                {
                    builder.AddLine(generated_code_attribute);
                    builder.BeginLine();
                    if (slot.GetAccessibility < slot.PropertyAccessibility)
                    {
                        builder.Add($"{getAccess} ");
                    }
                    builder.Add("get");
                    builder.EndLine();

                    using (builder.BlockScope())
                    {
                        builder.AddLines($"""
                        {slotsBoundCheck(slot.PropertyName)}
                        var _span = base.DunderSlots.Span;
                        """);

                        if (!slot.IsTypeNullable)
                        {
                            builder.AddLines($"""
                            var _value = _span[{slotIndex(slot.PropertyName)}];
                            if (_value == null)
                                throw new global::System.NullReferenceException("'{slot.PropertyName}' slot value is null.");
                            return ({slot.TypeString})_value;
                            """);
                        }
                        else
                        {
                            builder.AddLine($"return ({slot.TypeString})_span[{slotIndex(slot.PropertyName)}];");
                        }
                    }

                    builder.AddLine(generated_code_attribute);
                    builder.BeginLine();
                    if (slot.SetAccessibility < slot.PropertyAccessibility)
                    {
                        builder.Add($"{setAccess} ");
                    }
                    builder.Add("set");
                    builder.EndLine();

                    using (builder.BlockScope())
                    {
                        builder.AddLines($"""
                        {slotsBoundCheck(slot.PropertyName)}

                        var _span = base.DunderSlots.Span;
                        _span[{slotIndex(slot.PropertyName)}] = value;
                        """);
                    }
                }
                builder.BlankLine();

                builder.AddLines($"""
                // Index of the slot '{slot.DescriptorName}'
                {generated_code_attribute}
                private const int {slotIndex(slot.PropertyName)} = {classSlotCount(target.BaseClassName)} + {i};
                """);
            }
        }

        var sourceText = SourceText.From(builder.ToString(), Encoding.UTF8);

        context.AddSource(target.Identifier, sourceText);

        static string slotsBoundCheck(string propertyName)
        {
            return $"""
            if (base.DunderSlots.Length <= {slotIndex(propertyName)})
                throw new global::System.Diagnostics.UnreachableException("Slot '{propertyName}' access error: slots have less size then slot index.");
            """;
        }

        static string slotIndex(string propertyName) => $"_{propertyName}_Index";

        static string classSlotCount(string className) => $"_{className}SlotCount";

        static string getAccessibilityString(Accessibility accessibility) => accessibility switch
        {
            Accessibility.NotApplicable => "",
            Accessibility.Private => "private",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.Public => "public",

            _ => throw new InvalidOperationException(),
        };
    }

    private record TargetData(
        string Namespace,
        string ClassName,
        string BaseClassName,
        ValueArray<SlotData> Slots)
    {
        public string Identifier => $"{Namespace}+{ClassName}_{Slots.Length}.g.cs";
    }

    private record SlotData(
        string PropertyName,
        string DescriptorName,
        string TypeName,
        bool IsTypeNullable,
        Accessibility PropertyAccessibility,
        Accessibility GetAccessibility,
        Accessibility SetAccessibility)
    {
        public string TypeString => TypeName + (IsTypeNullable ? "?" : "");
    }
}
