# The file is a 'translation' from the Python grammar of CPython.
# Copyright (c) 2001 Python Software Foundation; All Rights Reserved

# Grammar metadata
# ================

@header '''\
using Epoxid.SyntaxAnalysis.Tokens;
using Epoxid.SyntaxAnalysis.Common;
using Epoxid.SyntaxAnalysis.Common.Ast;
'''
@parser_name 'PythonParser'
@access 'public'
@namespace 'Epoxid.SyntaxAnalysis'

@keywords = [
    False,
    None,
    True,
    and,
    as,
    assert,
    async,
    await,
    break,
    case,
    class,
    continue,
    def,
    del,
    elif,
    else,
    except,
    finally,
    for,
    from,
    global,
    if,
    import,
    in,
    is,
    lambda,
    match,
    nonlocal,
    not,
    or,
    pass,
    raise,
    return,
    try,
    while,
    with,
    yield,
]

# === Grammar Start ===

# Starting rules
# ==============

@main
File: Statement* EndOfFile -> new(Statements=statement_Star)

# General statements
# ==================

@union
Statement:
    | CompoundStatement
    | SimpleStatements

SimpleStatements:
    | SimpleStatement !';' NewLine -> SingleSimpleStatement(Value=simple_statement)
    | SimpleStatement+.';' -';' NewLine -> SeparatedSimpleStatements(Values=simple_statement_Gather)

@union
SimpleStatement:
    | Assignment
    | &'type'       TypeAlias
    | &ImportStart  ImportStatement
    | StarExpressionVariant
    | &'return'     ReturnStatement
    | &'raise'      RaiseStatement
    | &'pass'       PassStatement
    | &'del'        DeleteStatement
    | &'yield'      YieldStatement
    | &'assert'     AssertStatement
    | &'break'      BreakStatement
    | &'continue'   ContinueStatement
    | &'global'     GlobalStatement
    | &'nonlocal'   NonlocalStatement

@inline
ImportStart:
    | 'from'
    | 'import'
    | 'lazy'

@union
CompoundStatement:
    | &(@inline 'def' | '@' | 'async') FunctionDef

    | &'if' IfStatement

    | &(@inline 'class' | '@') ClassDef

    | &(@inline 'with' | 'async') WithStatement

    | &(@inline 'for' | 'async') ForStatement

    | &'try' TryStatement

    | &'while' WhileStatement

    # NSY | MatchStatement

# Simple statements
# =================

Assignment:
    | Name ':' Expression -EqualAnnotatedRhs -> AnnotatedAssignment(Target=name, TypeHint=expression, Rhs=equal_annotated_rhs)

    | Name EqualAnnotatedRhs -> SimpleAssignment(Target=name, Rhs=equal_annotated_rhs)

    | '(' SingleTarget ')' ':' Expression -EqualAnnotatedRhs -> AnnotatedParenthesizedAssignment(
        Target=single_target, TypeHint=expression, Rhs=equal_annotated_rhs)

    | SingleSubscriptAttributeTarget ':' Expression -EqualAnnotatedRhs -> AnnotatedSubscriptAttributeAssignment(
        Target=single_subscript_attribute_target, TypeHint=expression, Rhs=equal_annotated_rhs)

    | (AssignmentTargetVariant '=' -> CascadeTarget(Value=assignment_target_variant))+ AnnotatedRhs !'=' -> CascadeAssignment(
        Targets=cascade_target_Plus, Rhs=annotated_rhs)

    | SingleTarget AugAssign ~ AnnotatedRhs -> AugmentedAssignment(Target=single_target, Operator=aug_assign, Rhs=annotated_rhs)

EqualAnnotatedRhs: '=' AnnotatedRhs -> new(Value=annotated_rhs)

@inline
AugAssign:
    | '+='
    | '-='
    | '*='
    | '@='
    | '|='
    | '%='
    | '&='
    | '|='
    | '^='
    | '<<='
    | '>>='
    | '**='
    | '|='

@union
AnnotatedRhs:
    | YieldExpression
    | StarExpressionVariant

ReturnStatement: 'return' -StarExpressionVariant -> new(Expression=star_expression_variant)

RaiseStatement:
    | 'raise' Expression 'from' Expression -> RaiseFromStatement(NewException=expression, OldExpression=expression1)
    | 'raise' Expression -> RaiseFromScratchStatement(Exception=expression)
    | 'raise' -> PassedRaiseStatement()

PassStatement: 'pass' -> new()

BreakStatement: 'break' -> new()

ContinueStatement: 'continue' -> new()

GlobalStatement: 'global' Name+.',' -> new(Variables=name_Gather)

NonlocalStatement: 'nonlocal' Name+.',' -> new(Variables=name_Gather)

DeleteStatement: 'del' DeleteTarget+.',' -',' &(@inline ';' | NewLine) -> new(Targets=delete_target_Gather)

YieldStatement: YieldExpression -> new(Expression=yield_expression)

AssertStatement: 'assert' Expression [',' Expression -> AssertMessage(Value=expression)] -> new(Guard=expression, Message=assert_message)

@union
@memo
ImportStatement:
    | ImportName
    | LazyImportName
    | ImportFrom
    | LazyImportFrom

# Import Statements
# =================

# CPython uses the `?` (`-` here) and NULL check for lazy. But it feels more like a hack, so make different rules for that.
# If changed: don't forget to change lazy also because it's just copypaste.

ImportName: 'import' DottedName+.',' -> new(Import=dotted_name_Gather)

LazyImportName: 'lazy' 'import' DottedName+.',' -> new(Import=dotted_name_Gather)

DottedName: ImportUnit ['as' Name -> AsName(Value=name)] -> new(Name=import_unit, Alias=as_name)

ImportFrom:
    | 'from' RelativeImportDots* ImportUnit 'import' ImportFromTargets -> ImportFromModule(
        RelativePath=relative_import_dots_Star, Path=import_unit, Targets=import_from_targets)

    | 'from' RelativeImportDots+ 'import' ImportFromTargets -> ImportFromRelative(
        RelativePath=relative_import_dots_Plus, Targets=import_from_targets)

LazyImportFrom:
    | 'lazy' 'from' RelativeImportDots* ImportUnit 'import' ImportFromTargets -> LazyImportFromModule(
        RelativePath=relative_import_dots_Star, Path=import_unit, Targets=import_from_targets)

    | 'lazy' 'from' RelativeImportDots+ 'import' ImportFromTargets -> LazyImportFromRelative(
        RelativePath=relative_import_dots_Plus, Targets=import_from_targets)

@inline
RelativeImportDots:
    | '.'
    | '...'  # Necessary because it tokenized as Ellipsis

ImportFromTargets:
    | '(' AliasedName+.',' -',' ')' -> ImportFromGroup(Targets=aliased_name_Gather)
    | AliasedName+.',' !',' -> ImportFromNames(Targets=aliased_name_Gather)
    | '*' -> ImportAll()

AliasedName: Name ['as' Name -> AsName(Value=name)] -> new(Name=name, Alias=as_name)

@memo
ImportUnit:
    | ImportUnit '.' Name -> DottedImportUnit(Left=import_unit, Right=name)
    | Name -> SingleImportUnit(Value=name)

# Compound Statements
# ===================

# Common nodes
# ------------

@memo
Block:
    | NewLine Indent Statement+ Dedent -> IndentedBlock(Statements=statement_Plus)
    | SimpleStatements -> OneLinedBlock(Statements=simple_statements)

Decorator: '@' NamedExpression NewLine -> new(Value=named_expression)

# Class definitions
# -----------------

ClassDef:
    | Decorator* ClassDefRaw -> DecoratedClassDef(Decorators=decorator_Star, ClassDef=class_def_raw)
    | ClassDefRaw -> RawClassDef(Value=class_def_raw)

ClassDefRaw: 'class' Name -TypeParameters ['(' -Arguments ')' -> ClassDefArgs(Value=arguments)] ':' Block -> new(
        Name=name, 
        TypeParameters=type_parameters, 
        Arguments=class_def_args, 
        Block=block)

# Function definitions
# --------------------

FunctionDef:
    | Decorator* FunctionDefRaw -> new(Decorators=decorator_Star, FunctionDef=function_def_raw)

FunctionDefRaw:
    | 'def' Name -TypeParameters '(' -Parameters ')' ['->' Expression -> FunctionReturnHint(Value=expression)] ':' Block -> \
        SyncFunctionDef(Name=name, TypeParameters=type_parameters, Parameters=parameters, ReturnHint=function_return_hint, Block=block)

    | 'async' Name -TypeParameters '(' -Parameters ')' ['->' Expression -> FunctionReturnHint(Value=expression)] ':' Block -> \
        AsyncFunctionDef(Name=name, TypeParameters=type_parameters, Parameters=parameters, ReturnHint=function_return_hint, Block=block)

# In original grammar parser forces from code to use proper orders of default values and sections 
# but it makes output AST hierarchy very complicated, so better to validate it when compiling.
Parameters: Parameter+.',' -',' -> new(Parameters=parameter_Gather)

Parameter:
    | Param '=' Expression -> ParameterDefault(Param=param, DefaultValue=expression)
    | Param -> OrdinalParameter(Param=param)
    | '*' Param -> PositionalVariadicParameter(Param=param)
    | '**' Param -> KeywordVariadicParameter(Param=param)
    | '*' -> KeywordOnlyMarker()
    | '/' -> PositionalOnlyMarker()

Param: Name [':' Expression -> Annotation(Expression=expression)] -> new(
    Name=name, Annotation=annotation)

# If statement
# ------------

IfStatement:
    | 'if' NamedExpression ':' Block ElifStatement* -ElseBlock -> new(
        Condition=named_expression, Block=block, Elifs=elif_statement_Star, Else=else_block)

ElifStatement: 'elif' NamedExpression ':' Block -> new(Condition=named_expression, Block=block)

ElseBlock: 'else' ':' Block -> new(Block=block)

# While statement
# ---------------

WhileStatement: 'while' NamedExpression ':' Block -ElseBlock -> new(Condition=named_expression, Block=block, Else=else_block)

# For statement
# -------------

ForStatement:
    | 'for' AssignmentTargetVariant 'in' ~ StarExpressionVariant ':' Block -ElseBlock -> NormalForStatement(
        Targets=assignment_target_variant, Expression=star_expression_variant, Block=block, Else=else_block)

    | 'async' 'for' AssignmentTargetVariant 'in' ~ StarExpressionVariant ':' Block -ElseBlock -> AsyncForStatement(
        Targets=assignment_target_variant, Expression=star_expression_variant, Block=block, Else=else_block)

# With statement
# --------------

WithStatement:
    | 'with' '(' WithItem+.',' -',' ')' ':' Block -> ParenthesizedWithStatement(Items=with_item_Gather, Block=block)
    | 'with' WithItem+.',' ':' Block -> OneLinedWithStatement(Items=with_item_Gather, Block=block)
    | 'async' 'with' '(' WithItem+.',' -',' ')' ':' Block -> ParenthesizedAsyncWithStatement(Items=with_item_Gather, Block=block)
    | 'async' 'with' WithItem+.',' ':' Block -> OneLinedAsyncWithStatement(Items=with_item_Gather, Block=block)

WithItem:
    | Expression 'as' AssignmentTarget &(@inline ',' | ')' | ':') -> NamedWithItem(Expression=expression, Target=assignment_target)
    | Expression -> PlainWithItem(Expression=expression)

# Try statement
# -------------

TryStatement:
    | 'try' ':' Block FinallyBlock -> TryFinallyStatement(Try=block, Finally=finally_block)

    | 'try' ':' Block ExceptBlock+ -ElseBlock -FinallyBlock -> TryExceptStatement(
        Try=block, Excepts=except_block_Plus, Else=else_block, Finally=finally_block)

    | 'try' ':' Block ExceptStarBlock+ -ElseBlock -FinallyBlock -> TryExceptStarStatement(
        Try=block, Excepts=except_star_block_Plus, Else=else_block, Finally=finally_block)

ExceptBlock:
    | 'except' Expression ':' Block -> PlainExceptBlock(Exception=expression, Block=block)
    | 'except' Expression 'as' Name ':' Block -> AliasExceptBlock(Exception=expression, Alias=name, Block=block)
    | 'except' Expression+.',' -',' ':' Block -> MultipleExceptBlock(Exceptions=expression_Gather, Block=block)
    | 'except' ':' Block -> EmptyExceptBlock(Block=block)

ExceptStarBlock:
    | 'except' '*' Expression ':' Block -> PlainExceptStarBlock(Exception=expression, Block=block)
    | 'except' '*' Expression 'as' Name ':' Block -> AliasExceptStarBlock(Exception=expression, Alias=name, Block=block)
    | 'except' '*' Expression+.',' -',' ':' Block -> MultipleExceptStarBlock(Exceptions=expression_Gather, Block=block)

FinallyBlock: 'finally' ':' Block -> new(Value=block) 

# Match statement
# ---------------

# SKIPPA SKIPPA

# Type statement
# --------------

TypeAlias: 'type' Name -TypeParameters '=' Expression -> new(Name=name, TypeParameters=type_parameters, Value=expression)

TypeParameters: '[' TypeParameter+.',' -',' ']' -> new(Values=type_parameter_Gather)

@memo
TypeParameter:
    | Name -TypeParameterBound -TypeParameterDefault
    | Name '*' -TypeParameterStarredDefault
    | Name '**' -TypeParameterDefault

TypeParameterBound: ':' Expression -> new(Value=expression)

TypeParameterDefault: '=' Expression -> new(Value=expression)

TypeParameterStarredDefault: '=' StarExpression -> new(Value=star_expression)

# Expressions
# ===========

# Top level expressions
# ---------------------

@union
@memo
Expression:
    | IfExpression
    | Disjunction
    | BitwiseOrExpression
    # NSY | LambdaDef

IfExpression: Arithmetic 'if' Arithmetic 'else' Expression -> new(Condition=arithmetic1, Then=arithmetic, Else=expression)

@union
Arithmetic:
    | Disjunction
    | BitwiseOrExpression

YieldExpression:
    | 'yield' 'from' Expression -> YieldFromExpression(Expression=expression)
    | 'yield' -StarExpressions -> YieldStarExpression(Expression=star_expressions)

@union
StarExpressionVariant:
    | StarExpression !','
    | StarExpressions

StarExpressions: StarExpression+.',' -',' -> new(Values=star_expression_Gather)

@union
@memo
StarExpression:
    | StarBitwiseOrExpression
    | Expression

StarBitwiseOrExpression: '*' BitwiseOrExpression -> new(Value=bitwise_or_expression)

@union
StarNamedExpression:
    | StarBitwiseOrExpression
    | NamedExpression

StarNamedExpressions: StarNamedExpression+.',' -',' -> new(Items=star_named_expression_Gather)

AssignmentExpression: Name ':=' ~ Expression -> new(Target=name, Value=expression)

@union
NamedExpression:
    | AssignmentExpression
    | Expression !':='

@memo
Disjunction: Conjunction+.'or' -> new(Conjunctions=conjunction_Gather)

@memo
Conjunction: InversionExpression+.'and' -> new(Inversions=inversion_expression_Gather)

@union
@memo
InversionExpression:
    | Inversion
    | Comparison

Inversion: 'not' InversionExpression -> new(Inversion=inversion_expression)

# Comparison operators
# --------------------

Comparison: BitwiseOrExpression CompareOperation+ -> new(
    First=bitwise_or_expression, Rest=compare_operation_Plus)

# Cannot use `@inline` because some operators is 2 tokens wide.
CompareOperation:
    | '==' BitwiseOrExpression        -> EqOperation(Right=bitwise_or_expression)
    | '!=' BitwiseOrExpression        -> NotEqOperation(Right=bitwise_or_expression)
    | '<=' BitwiseOrExpression        -> LtEqOperation(Right=bitwise_or_expression)
    | '<' BitwiseOrExpression         -> LtOperation(Right=bitwise_or_expression)
    | '>=' BitwiseOrExpression        -> GtEqOperation(Right=bitwise_or_expression)
    | '>' BitwiseOrExpression         -> GtOperation(Right=bitwise_or_expression)
    | 'not' 'in' BitwiseOrExpression  -> NotInOperation(Right=bitwise_or_expression)
    | 'in' BitwiseOrExpression        -> InOperation(Right=bitwise_or_expression)
    | 'is' 'not' BitwiseOrExpression  -> IsNotOperation(Right=bitwise_or_expression)
    | 'is' BitwiseOrExpression        -> IsOperation(Right=bitwise_or_expression)

# Bitwise operators
# -----------------

@union
@memo
BitwiseOrExpression:
    | BitwiseOr
    | BitwiseXorExpression

BitwiseOr: BitwiseOrExpression '|' BitwiseXorExpression -> new(Left=bitwise_or_expression, Right=bitwise_xor_expression)

@union
@memo
BitwiseXorExpression:
    | BitwiseXor
    | BitwiseAndExpression

BitwiseXor: BitwiseXorExpression '^' BitwiseAndExpression -> new(Left=bitwise_xor_expression, Right=bitwise_and_expression)

@union
@memo
BitwiseAndExpression:
    | BitwiseAnd
    | BitShiftExpression

BitwiseAnd: BitwiseAndExpression '&' BitShiftExpression -> new(Left=bitwise_and_expression, Right=bit_shift_expression)

@union
@memo
BitShiftExpression:
    | BitShift
    | SumExpression

BitShift: BitShiftExpression BitShiftOperator SumExpression -> new(
    Left=bit_shift_expression, Right=sum_expression, Operator=bit_shift_operator)

@inline
BitShiftOperator:
    | '<<'
    | '>>'

# Arithmetic operators
# --------------------

@union
@memo
SumExpression:
    | Sum
    | TermExpression

Sum: SumExpression SumOperator TermExpression -> new(Left=sum_expression, Right=term_expression, Operator=sum_operator)

@inline
SumOperator:
    | '+'
    | '-'

@union
@memo
TermExpression:
    | Term
    | FactorExpression

Term: TermExpression TermOperator FactorExpression -> new(
    Left=term_expression, Right=factor_expression, Operator=term_operator)

@inline
TermOperator:
    | '*'
    | '/'
    | '//'
    | '%'
    | '@'

@union
@memo
FactorExpression:
    | Factor
    | PowerExpression

Factor: FactorOperator FactorExpression -> new(Operator=factor_operator, Value=factor_expression)

@inline
FactorOperator:
    | '+'
    | '-'
    | '~'

@union
@memo
PowerExpression:
    | Power
    | Primary  # Terminal

Power: Primary '**' FactorExpression -> new(Left=primary, Right=factor_expression)

# Primary elements
# ----------------

@union
Primary:
    | AwaitPrimary
    | RawPrimary

AwaitPrimary: 'await' RawPrimary -> new(Value=raw_primary)

@memo
RawPrimary:
    | RawPrimary '.' Name -> DotOperationPrimary(Left=raw_primary, Right=name)
    | RawPrimary GeneratorExpression -> CallWithGeneratorPrimary(Function=raw_primary, Argument=generator_expression)
    | RawPrimary '(' -Arguments ')' -> CallWithArgumentsPrimary(Function=raw_primary, Arguments=arguments)
    | RawPrimary '[' Slices ']' -> SubscriptPrimary(Target=raw_primary, Subscript=slices)
    | Atom -> AtomPrimary(Atom  =atom)

Slices:
    | Slice !',' -> OneSliceSubscript(Value=slice)
    | Dimension+.',' -',' -> DimensionalSubscript(Values=dimension_Gather)

Dimension:
    | Slice -> DimensionSlice(Value=slice) 
    | StarExpression -> DimensionExpression(Value=star_expression)

Slice:
    | NamedExpression -> NamedSliceExpression(Value=named_expression)

    | -Expression ':' -Expression [':' -Expression -> StepSliceParam(Value=expression)] -> ColonSlice(
        Start=expression, End=expression1, Step=step_slice_param)

@union
Atom:
    | OneTokenAtom
    | &(@inline StringLiteral | FStringStart | TStringStart) StringAtom
    | &'(' GeneratorExpression
    | &'(' Tuple
    | &'(' Group
    | &'[' ListComprehension
    | &'[' List
    | &'{' DictComprehension
    | &'{' SetComprehension
    | &'{' Dict
    | &'{' Set

OneTokenAtom:
    | Name -> NameAtom(Value=name)
    | 'True' -> TrueAtom()
    | 'False' -> FalseAtom()
    | 'None' -> NoneAtom()
    | Number -> NumberAtom(Value=number)
    | '...' -> EllipsisAtom()

Group:
    | '(' NamedExpression ')' -> NamedGroupExpression(Value=named_expression)
    | '(' YieldExpression ')' -> YieldGroupExpression(Value=yield_expression)

# Lambda functions
# ----------------

# SKIPPA SKIPPA

# Literals
# ========

FString: FStringStart FStringValue* FStringEnd -> new(Header=f_string_start, Values=f_string_value_Star)

FStringValue:
    | FStringMiddle -> FStringValueLiteral(Value=f_string_middle)
    | FStringReplacementField -> FStringValueReplacement(Value=f_string_replacement_field)

FStringReplacementField: 
    | '{' AnnotatedRhs -DebugSpecifier -Conversion -FStringFullFormatSpec '}' -> new(
        Value=annotated_rhs, DebugSpecifier=debug_specifier, Conversion=conversion, FormatSpec=f_string_full_format_spec)
    
FStringFullFormatSpec: ':' FStringFormatSpec* -> new(Specs=f_string_format_spec_Star)

FStringFormatSpec:
    | FStringMiddle -> FStringFormatLiteral(Value=f_string_middle)
    | FStringReplacementField -> FStringFormatReplacement(Value=f_string_replacement_field)

TString: TStringStart TStringValue* TStringEnd -> new(Header=t_string_start, Values=t_string_value_Star)

TStringValue:
    | TStringMiddle -> TStringValueLiteral(Value=t_string_middle)
    | TStringReplacementField -> TStringValueReplacement(Value=t_string_replacement_field)

TStringReplacementField: '{' AnnotatedRhs -DebugSpecifier -Conversion -TStringFullFormatSpec '}' -> new(
    Value=annotated_rhs, DebugSpecifier=debug_specifier, Conversion=conversion, FormatSpec=t_string_full_format_spec)

TStringFullFormatSpec: ':' TStringFormatSpec* -> new(Specs=t_string_format_spec_Star)

TStringFormatSpec:
    | TStringMiddle -> TStringFormatLiteral(Value=t_string_middle)
    | TStringReplacementField -> TStringFormatReplacement(Value=t_string_replacement_field)

DebugSpecifier: '=' -> new()

Conversion: '!' Name -> new(Value=name)

@memo
StringAtom:
    | StringValue+ -> StringValueAtom(Parts=string_value_Plus)
    | TString+ -> StringTemplateAtom(Parts=t_string_Plus)

StringConstant: StringLiteral -> new(Value=string_literal)

@union
StringValue:
    | StringConstant
    | FString

List: '[' -StarNamedExpressions ']' -> new(Items=star_named_expressions)

Tuple: '(' StarNamedExpression ',' -StarNamedExpressions ')' -> new(First=star_named_expression, Rest=star_named_expressions)

Set: '{' StarNamedExpressions '}' -> new(Items=star_named_expressions)

# Dicts
# -----

Dict: '{' -StarredOrKeyValues '}' -> new(KeyValuePairs=starred_or_key_values)

StarredOrKeyValues: StarredOrKeyValue+.',' -',' -> new(Items=starred_or_key_value_Gather)

StarredOrKeyValue:
    | '**' BitwiseOrExpression -> DoubleStarred(Value=bitwise_or_expression)
    | Expression ':' Expression -> KeyValuePair(Key=expression, Value=expression1)

# Comprehensions and Generators
# -----------------------------

ForIfClause:
    | 'async' 'for' AssignmentTargetVariant 'in' ~ Disjunction ('if' Disjunction -> IfClause(Condition=disjunction))* -> AsyncForIfClause(
        Variables=assignment_target_variant, Iterable=disjunction, Conditions=if_clause_Star)
    
    | 'for' AssignmentTargetVariant 'in' ~ Disjunction ('if' Disjunction -> IfClause(Condition=disjunction))* -> NormalForIfClause(
        Variables=assignment_target_variant, Iterable=disjunction, Conditions=if_clause_Star)

ListComprehension: '[' StarNamedExpression ForIfClause+ ']' -> new(Expression=star_named_expression, Iterators=for_if_clause_Plus)

SetComprehension: '{' StarNamedExpression ForIfClause+ '}' -> new(Expression=star_named_expression, Iterators=for_if_clause_Plus)

GeneratorExpression: '(' StarNamedExpression ForIfClause+ ')' -> new(Expression=star_named_expression, Iterators=for_if_clause_Plus)

DictComprehension: 
    | '{' Expression ':' Expression ForIfClause+ '}' -> KeyValueDictComprehension(Key=expression, Value=expression1, Iterators=for_if_clause_Plus)
    | '{' '**' Expression ForIfClause+ '}' -> UnpackingDictComprehension(Expression=expression, Iterators=for_if_clause_Plus)

# Function call arguments
# =======================

@memo
Arguments:
    | PositionalArgument+.',' [',' Kwargs -> KeywordArgumentsPart(Value=kwargs)] -',' -> ArgumentsWithPositional(
        PositionalArgumentsPart=positional_argument_Gather, KeywordArgumentsPart=keyword_arguments_part)

    | Kwargs -',' -> ArgumentsWithOnlyKeywords(Value=kwargs)

@union
PositionalArgument:
    | StarredExpression !'='
    | NamedExpression !'='

Kwargs:
    | KwargOrStarred+.',' ',' KwargOrDoubleStarred+.',' -> BothStarredKwargs(
        OneStarred=kwarg_or_starred_Gather, DoubleStarred=kwarg_or_double_starred_Gather)

    | KwargOrStarred+.',' -> OneStarredKwargs(Items=kwarg_or_starred_Gather)

    | KwargOrDoubleStarred+.',' -> DoubleStarredKwargs(Items=kwarg_or_double_starred_Gather)

@union
KwargOrStarred:
    | Kwarg
    | StarExpression

@union
KwargOrDoubleStarred:
    | Kwarg
    | DoubleStarredExpression

DoubleStarredExpression: '**' Expression -> new(Expression=expression)

StarredExpression: '*' Expression -> new(Expression=expression)

Kwarg: Name '=' Expression -> new(Keyword=name, Value=expression)

# Assignment targets
# ==================

@union
AssignmentTargetVariant:
    | AssignmentTarget !','
    | AssignmentTargets

AssignmentTargets: AssignmentTarget+.',' -',' -> new(Targets=assignment_target_Gather)

@union
AssignmentTarget:
    | StarredAssignmentTarget
    | AssignmentTargetUnit

StarredAssignmentTarget: '*' AssignmentTargetUnit -> new(Target=assignment_target_unit)

@union
AssignmentTargetUnit:
    | DottedTargetUnit
    | SubscriptTargetUnit
    | AssignmentTargetAtom

DottedTargetUnit: TargetPrimary '.' Name !TargetPrimaryContinuation -> new(Left=target_primary, Right=name)

SubscriptTargetUnit: TargetPrimary '[' Slices ']' !TargetPrimaryContinuation -> new(Primary=target_primary, Subscript=slices)

AssignmentTargetAtom:
    | Name -> NameTargetAtom(Value=name)
    | '(' AssignmentTargetUnit ')' -> GroupedTargetAtom(Target=assignment_target_unit)
    | '(' -AssignmentTargets ')' -> TupleTargetAtom(Items=assignment_targets)
    | '[' -AssignmentTargets ']' -> ListTargetAtom(Items=assignment_targets)

SingleTarget:
    | SingleSubscriptAttributeTarget -> CompositeSingleTarget(Value=single_subscript_attribute_target)
    | Name -> NameSingleTarget(Value=name)
    | '(' SingleTarget ')' -> GroupedTarget(Target=single_target)

SingleSubscriptAttributeTarget:
    | TargetPrimary '.' Name !TargetPrimaryContinuation -> SingleAttributeTarget(Primary=target_primary, AttributeName=name)
    | TargetPrimary '[' Slices ']' !TargetPrimaryContinuation -> SingleSubscriptTarget(Primary=target_primary, Subscript=slices)

@memo
TargetPrimary:
    | TargetPrimary '.' Name &TargetPrimaryContinuation -> AttributeTarget(Primary=target_primary, AttributeName=name)
    | TargetPrimary '[' Slices ']' &TargetPrimaryContinuation -> SubscriptTarget(Primary=target_primary, Subscript=slices)
    | TargetPrimary GeneratorExpression &TargetPrimaryContinuation -> GeneratorTarget(Primary=target_primary, Generator=generator_expression)
    | TargetPrimary '(' -Arguments ')' &TargetPrimaryContinuation -> CallTarget(Primary=target_primary, Arguments=arguments)
    | Atom &TargetPrimaryContinuation -> AtomTarget(Value=atom)

@inline
TargetPrimaryContinuation:
    | '('
    | '['
    | '.'


# Targets for delete statement
# ----------------------------

@memo
DeleteTarget:
    | TargetPrimary '.' Name !TargetPrimaryContinuation -> DeleteAttributeTarget(Primary=target_primary, AttributeName=name)
    | TargetPrimary '[' Slices ']' &TargetPrimaryContinuation -> DeleteSubscriptTarget(Primary=target_primary, Subscript=slices)
    | Name -> DeleteAtomTarget(Value=name)

# In Python also was another delete targets, but support it later
